### ISSUE TITLE
Binned data documentation - think it needs updating

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#10]
ddf documentation says "Currently, a binned analysis can only be done for method="ds" and eventually int.range will be incorporated into the dataframe."

I have a note that this is out of date... can this sentence be removed @dill if you confirm I can do it.

**Comment by dill** [comment]
Yes, this is out of date. There may be other mentions in the docs about point transects only being available for `method="ds"` too, that's also out of date.
