### ISSUE TITLE
merging the optimist2 branch

### ISSUE THREAD

**Issue by fpetersma** [DistanceDevelopment/mrds#102]
The optimist2 branch has been checked by me and should be ready for a second or even third par of eyes to go through it. I *think* that I updated the documentations for the functions correctly. There are a bunch of new scripts that contains the analytical derivates and everything associated with those, and several scripts have been updated to accommodate the new solver or to resolve some bugs that I encountered.

**Comment by LHMarshall** [comment]
This merge has now happened
