### ISSUE TITLE
Recycling array of length 1 in vector array arithmetic is deprecated

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#11]
@dill any ideas about this?

I only get it in the R-devel and currently it looks like I can upload without complaint... tempted to leave this for now. Think it is relevant to keyfct.hz and keyfct.hn or do I just have to put as.vector() around key.scale and key.shape?

![screen shot 2016-10-02 at 13 17 45](https://cloud.githubusercontent.com/assets/1295691/19022534/735e5e78-88d2-11e6-9ffc-1a65e5e3bc94.png)

**Comment by dill** [comment]
I think you need to ensure that `key.scale` is the same length as 
`distance`.

So something like:

```
if(length(key.scale) == 1){
   key.scale <- rep(key.scale, length(distance)
}
```

should do it.

You need to check length as key.scale does have the same length as 
distance in the case where covariates are in the scale parameter.

(I hadn't realised this was going to be a change and I think it's a good 
idea, though surely recycling of length>1 vectors is actually way more 
confusing... och well)

**Comment by LHMarshall** [comment]
Thanks @dill I did some more digging I discovered that key.scale is not a vector it is a matrix. For some calls it is a 162x1 matrix but for the final call it is a 1x1 matrix. Agree on the recycling of vectors > 1 that has endless possibilities for introducing bugs... although you do get a warnings if the shorter is not a multiple of the longer.

matrix
[1] 162   1
           [,1]
  [1,] 2.516874
  [2,] 2.516874
 ...
[161,] 2.516874
[162,] 2.516874
matrix
[1] 1 1
         [,1]
[1,] 2.516642

**Comment by LHMarshall** [comment]
@dill Turning those arguments into vectors keeps it happy (even if there is replication) that only appears to be a problem if there is a mix of vectors and matrices. Is there ever a situation when the matrix will have more than 1 column?

**Comment by dill** [comment]
I don't think there's any time it would be >1 column.

**Comment by LHMarshall** [comment]
@erex thought I had memories of this issue before... @dill I'm still a bit confused as to why the key.scale and key.shape are matrices and not vectors

**Comment by dill** [comment]
This is on my list for this week.

Those parameters are matrices because they are generated by z %*% pars in scalevalue() iirc.

If you have R 3.4 running somewhere I'll ping you to test, if that's okay?

**Comment by LHMarshall** [comment]
@dill sure ping away :)
