### ISSUE TITLE
Q-Q plot incorrect for left truncated data

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#12]
Q-Q plot on the left is with no left truncation, Q-Q plot on the right has left truncation

![screen shot 2017-01-19 at 12 53 55](https://cloud.githubusercontent.com/assets/1295691/23898013/49e0a5f6-08a7-11e7-9d88-980df5fb79f3.png)

**Comment by dill** [comment]
Yikes!

Confirmed via:

```r
library(mrds)
data(book.tee.data)
egdata <- book.tee.data$book.tee.dataframe
result <- ddf(dsmodel=~mcds(key="hn", formula=~1), data=egdata, method="ds",
                   meta.data=list(width=4))
par(mfrow=c(1,2))
ddf.gof(result)
result <- ddf(dsmodel=~mcds(key="hn", formula=~1), data=egdata, method="ds",
                  meta.data=list(width=4, left=1))
ddf.gof(result)
```

producing:

![screen shot 2017-03-14 at 10 01 40](https://cloud.githubusercontent.com/assets/1953/23904218/6d851668-089d-11e7-9024-2669be43ae98.png)

Will look into this today.

**Comment by dill** [comment]
fc18891 should fix this.
