### ISSUE TITLE
What does varn() return?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#20]
Documentation claims it returns a variance
https://github.com/DistanceDevelopment/mrds/blob/9f76f3816510e1688c75df00f9cbb6aca15f1292/R/varn.R#L30

but performing calculations by hand suggests what is calculated is actually cv^2

Can somebody verify?

**Comment by LHMarshall** [comment]
Is this a problem specific to point transects or both line and point transects? Also are you saying it returns cv^2 for all estimators or for one specific one?

**Comment by erex** [comment]
varn() wasn't designed for point transects; Dave has somewhat 'reverse-engineered' mrds for points.

I tracked the calculations for R2 (default).  Didn't examine other variance estimators

**Comment by dill** [comment]
um, to me...

```
 var.R2 <- (k * sum(lvec^2 * (nvec/lvec - ntot/L)^2))/(L^2 * (k -1))
```

looks like:

![screen shot 2017-11-30 at 07 33 10](https://user-images.githubusercontent.com/1953/33419098-d049c9bc-d5a0-11e7-826a-4c82ca085302.png)

**Comment by LHMarshall** [comment]
I conclude these are in fact the same and we can close this...

var = cv^2 * mu^2

cv^2 as per Eric's post above

mu^2 = n^2 / L^2 

giving the equation posted by Dave.
