### ISSUE TITLE
Unexpected behaviour in estimating density/abundance with left.truncation - distance sampling

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [DistanceDevelopment/mrds#22]
I'm estimating the detection function from multiple years of data and then applying it to the individual years of data. So I'm using mrds::ddf() to estimate the detection function and the mrds::dht() to estimate the individual year's abundances. 

However, animals near the transect line are in a blind spot which violates the assumption that animals on the detection line are estimated with prob =1. So I use the left= in the meta.data to set a left truncation value. This gives me a sensible detection function.

But when I apply this to the data, it correctly expands objects ONLY in the strip between the left= and width= in the meta.data, (i.e. ignored the objects from 0 to left), but computes density based on the full strip width, rather than (width-left) x length of transect which cases a negative bias in the density estimate. 

I would have expected the function to estimate density by also ignoring the strip between 0 and left.

I've created a little simulation (attached) to illustrate the problem. Notice that Nchat when using the left= gives the number of animals in each transect only between left and width, but the divides by the full area (including the left truncated part). 

It is possible to fix this using a "hack", but shouldn't dht() ignore the area of the strip between 0 and the left(). At the very least, a warning message should be printed warning the user that this occurred.

Am I missing something here?

I've include the R code and .html notebook file from the simulation.

Thanks
Carl Schwarz
[unexpected.zip](https://github.com/DistanceDevelopment/mrds/files/3507457/unexpected.zip)

**Comment by dill** [comment]
Thanks for the thorough bug report Carl, your diagnosis seems correct to me and I've made the requisite patch to the `dht` routine. Re-running your code, I now get that my `abund3` results match those of your `abund4`.

You can install this patched version via the `remotes` package with `remotes::install_github("DistanceDevelopment/mrds")`. Do let me know if that doesn't resolve the issue for you.

Thanks again for taking the time to report the bug!

**Comment by cschwarz-stat-sfu-ca** [comment]
Thanks for fixing this. Carl
