### ISSUE TITLE
Could not find function "integratepdf"

### ISSUE THREAD

**Issue by pgiraudoux** [DistanceDevelopment/mrds#25]
Hi,
Trying to use the function integratepdf, I get this message:

```
Error in integratepdf(fox.ds$ddf$ds$aux$ddfobj, select = rep(TRUE, nrow(fox.ds$ddf$ds$aux$ddfobj$xmat)),  : 
  could not find function "integratepdf"
```
Have you already had this issue ? Maybe not exported in the namespace?

**Comment by erex** [comment]
Just had a look in the `mrds` package, and I think you're right about that function not being exported in the namespace.  The function does exist in the package and a help entry does exist for it.  But it cannot be called without referencing the package it is in.

```
> integratepdf
Error: object 'integratepdf' not found
> mrds:::integratepdf
function (ddfobj, select, width, int.range, standardize = TRUE, 
    point = FALSE, left = 0, doeachint = FALSE) 
{
    if (!is.matrix(int.range)) {
        if (is.vector(int.range) && length(int.range) == 2) {
            int.range <- matrix(int.range, ncol = 2, nrow = 1)
        }
        else { .....
```
You can use `integratepdf` even if it is not exported with `mrds:::integratepdf(...)`
