### ISSUE TITLE
Nifty new functions documentation invisible to `Distance` users

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#29]
Lovely to have `add_df_covar_line` and `p_dist_table` functions.  However, for users of the `Distance` package, they do not know these functions exist, as they and their documentation live in `mrds`.  Some/many/lots of `Distance` users do not know that it hides `mrds`.  `Distance` exists to shield users of a gentile disposition from `mrds`.

Can the description of these two new functions be visible to users of `Distance`, without them having to deduce they need to look in the documentation of different package?

**Comment by dill** [comment]
Probably the best approach to this would be to show these in examples listed in the manual pages of existing functions in `Distance`, specifically `ds()`.

The other obvious outlet would be via revisiting existing vignettes on the example site and adding these where they might be most useful.

Finally it is possible to add documentation objects to `Distance` that are in fact in `mrds`, but I'll need to work out if there is a specific way one should do that.

**Comment by dill** [comment]
Related `Distance` issues now closed.
