### ISSUE TITLE
EDR with CI

### ISSUE THREAD

**Issue by zielinskipp** [DistanceDevelopment/mrds#36]
Hi,

is it possible to calculate EDR with confidence itervals via your family of packages. We are trying to switch from desktop app to R interface and I couldn't get that information with R.

**Comment by erex** [comment]
The short answer to your question is "yes" for the point estimate, but "non-trivial" for the confidence intervals.  Using this formula
![image](https://user-images.githubusercontent.com/330744/103358831-773a3380-4aae-11eb-93fe-3284625575bb.png)
you can solve for EDR (rho in the equation) given the square of the truncation distance (w) and the estimate of P_a that is produced by `summary(ds_object)` as

```
EDR <- sqrt(p_a * w^2)
```

To compute confidence interval bounds, you'll need se(EDR) and that can be computed from se(p_a) (provided by `summary(ds_object)` using the delta method approximation.  I'll have a further think about that approximation.

**Comment by erex** [comment]
A function to perform the transformation from P_a to EDR as well as produce the standard error and confidence interval bounds for EDR.

```
#' Effective detection radius and confidence interval from dsobject
#'
#' @param dsobject fitted model object for point transect data
#' @param alpha type I error rate, default to 0.05
#'
#' @details
#' The key step is converting CV(P_a) to CV(EDR), by dividing CV(P_a) by 2.
#'
#' @return
#' Named list containing
#' \itemize{
#'   \item EDR - effective detection radius
#'   \item se.EDR - standard error of effective detection radius
#'   \item ci.EDR - vector with lower and upper confidence bounds
#' }
#'
EDRtransform <- function(dsobject, alpha=0.05) {
  if(class(dsobject) != "dsmodel") stop("First argument must be a dsmodel object")
  if(!dsobject$ddf$meta.data$point) stop("EDR can only be computed for point transect data")
  summary.ds.model <- summary(dsobject)
  p_a <- summary.ds.model$ds$average.p
  se.p_a <- summary.ds.model$ds$average.p.se
  cv.p_a <- se.p_a / p_a
  w <- summary.ds.model$ds$width
  edr <- sqrt(p_a * w^2)
  se.edr <- cv.p_a/2 * edr
  degfree <- summary.ds.model$ds$n - length(summary.ds.model$ddf$par)
  t.crit <- qt(1 - alpha/2, degfree)
  se.log.edr <- sqrt(log(1 + (cv.p_a/2)^2))
  c.mult <- exp(t.crit * se.log.edr)
  ci.edr <- c(edr / c.mult, edr * c.mult)
  return(list(EDR=edr, se.EDR=se.edr, ci.EDR=ci.edr))
}
```
[EDR-transformfunction.pdf](https://github.com/DistanceDevelopment/mrds/files/5760173/EDR-transformfunction.pdf)

**Comment by lenthomas** [comment]
@dll, d'you think it's worth adding estimate of effective detection radius/effective strip width to summary output from mrds and/or ds objects?

**Comment by zielinskipp** [comment]
thank you so much ; D

**Comment by lenthomas** [comment]
After discussion with @dill, we will add this to the summary output from mrds and ds; I'll schedule for the release after next (developer time already fully commited for the next sheduled release).  Meantime, best to use the code that @erex provided, above.

**Comment by dill** [comment]
Adding an additional entry to the last table reported by `summary` seems fine.

Note that we don't provide CIs in `summary` output at the moment (for parameters, p, abundance in the covered region, etc), only point estimate, CV and standard error. Intervals *are* provided in `dht`/`dht2` output. The appropriate distributional approximations need to be worked-out/checked if we're going to provide intervals. We also need an additional argument in `summary` (`ci_width=`, say) to specify the interval to report.

If we do report CIs for EDR/ESW, then should it be reported for all the estimated parameters reported in `summary`? Starting down this road then raises the question of whether the confidence intervals reported for the model parameters (scale, shape, covariate pars etc) can be used to form, say a *F*-test (or chi^2 or whatever), and whether therefore users should do covariate selection based on corresponding p-values. I've not seen this done for detection functions, but perhaps I am living a sheltered life.

**Comment by lenthomas** [comment]
Hmm... good points.  I think we can follow the lead of mcds.exe, which provides SE for both detection function model parameters and derived parameters f(0)/h(0), p and ESW/EDR; it also provides percent CV and 95%CI for the derived parameters.  I agree we need to check distributional assumptions -- again I think we can follow mcds.exe, so long as we document what we do.
