### ISSUE TITLE
Issue 22 - left truncation cases biases in estimates seems to be back

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [DistanceDevelopment/mrds#39]
Hmm...issue 22 when left truncation cases biases in estimates seem to be back. I looked at the latest revised code and there is a cryptic note on line 242 of the dht.r 

```
# Scale up abundances to survey region    
# note that we don't need to account for left truncation, as    
# it is taken care of when calculating average detection prob (by setting    
# detection prob to 0 between 0 and left truncation distance)   
 width <- model$meta.data$width * options$convert.units
```

but it is not clear how to set the detection prob to 0 between 0 and the left truncation distance.

The previous code file shows that the 3rd case again leads to biased estimates.

Carl Schwarz

**Comment by dill** [comment]
Note to self: the change is related to DistanceDevelopment/Distance#75.

**Comment by dill** [comment]
Sorry @cschwarz-stat-sfu-ca, this bug re-entered due to another issue we had but I think it's ironed-out now in the latest version. Thanks again for reporting!
