### ISSUE TITLE
Plot for uniform with no adjustments is incorrect

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#59]
![image](https://user-images.githubusercontent.com/1295691/194172921-e0e8f921-fefe-473a-842a-f4c25ff0795f.png)

think it should be this

![image](https://user-images.githubusercontent.com/1295691/194173022-bac085f7-7d58-472e-ba7d-867b000b6a61.png)

**Comment by lenthomas** [comment]
Certainly looks better!

**Comment by lenthomas** [comment]
BTW, @LHMarshall, looking at your fix, it's worth testing this works as you expect with left-truncated data.  It should, but worth double-checking - for estimated p, var(p) and N or D.  (See [here](https://github.com/DistanceDevelopment/Distance/issues/135) for some current difficulties with left truncation, as an example of things going wrong.)
