### ISSUE TITLE
Switch to P2 default encounter rate variance for point transects

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/mrds#65]
To match Distance for Windows, per changes from Fewster et al (2009).

Reference DistanceDevelopment/Distance#135

**Comment by lenthomas** [comment]
Suggest we put a notice about this on startup for `mrds` and `Distance` for this release and then remove again at a later time.

**Comment by LHMarshall** [comment]
Added a message at startup 
<img width="449" alt="image" src="https://github.com/DistanceDevelopment/mrds/assets/1295691/e29fbc7b-8f41-4b48-8b06-8e149226e5fe">
