### ISSUE TITLE
Linking in the mcds.exe optimization engine to fit dsmodels

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/mrds#66]
This project will enable the mcds.exe FORTRAN program to be called from `ddf`, to obtain ML parameter estimates for CDS and MCDS models.  The parameter estimates will be run through the `ddf` internals so that what emerges is a fitted `ddf` object.  It can be used for models of type `ds` and also for the `dsmodel` component of double observer point independence models.  The new facilities will be accessed via an option in the `control` list of the `ddf` call, for example `dsengine=`.  Options would be `R`, the default, which is to use the current engine, `mcds`, which means use mcds.exe, and `both` which means both will be used and the one with lowest -LnL retained (option names subject to change).  In the case of `both` it would be good if they ran in parallel.  A possible further option (likely for a future release) would be `mcds_first` (or some such name), which would use the `mcds` engine to provide starting values for the `R` engine.

A new function will also be added to download mcds.exe from some internet location and put it into the `inst` directory of the `mrds` package, from where it will be called.

**Comment by dill** [comment]
This is happening on the [`mcds-dot-exe`](https://github.com/DistanceDevelopment/mrds/tree/mcds-dot-exe) branch.

**Comment by dill** [comment]
Notes:

 - see also the `Distance` PR (may need to stricly depend on this version of `mrds` else you can't turn `MCDS.exe` analysis off)
 - Download location for `MCDS.exe` is totally arbitrary and based on what was quickest to type
 - [Jonah's repo](https://github.com/jonah417/summer_project) is here with @jonah417's work on this. Jonah will e-mail when they're done with their part of this and it should be a case of removing `create_command_file` and replacing with relevant functions from the above repo.
 - Possible bounds, initial values settings need to be fiddled with to ensure that `MCDS.exe` uses it's own values and doesn't always expect user input on these arguments.
 - To test, run `download_MCDS_dot_exe()`, then run in debug mode (`showit>=1`) to see what `ddf` is doing and which engine's model it picks (and to check `MCDS.exe` is working).
 - Tested on macOS (Intel/Monterey) with `wine`, Debian linux (Intel) in a Docker container and on bluewhale (Intel/Windows).
