### ISSUE TITLE
Readme.md file out of date

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#77]
readme file states 

> Otherwise:
> - One can download a Windows package binary using the ["Releases" tab in github](https://github.com/DistanceDevelopment/mrds/releases). To install in R, from the R menu, use "Packages\Install from Local Zip file" and browse to location of downloaded zip.

But there have been no releases since 2017 according to 
![image](https://user-images.githubusercontent.com/330744/224677917-eb4705ad-fd9c-41f8-a74f-d250b31eb23e.png)

**Comment by lenthomas** [comment]
This will be resolved when Laura makes the next release, so I'm going to mark it as fixed.
