### ISSUE TITLE
mcds-dot-exe under Linux

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#88]
At some point, the "dual analysis" `mrds` package (with `Distance`) should be tested not only under Windows and MacOS, but also under Linux, perhaps using Isbjorn. This is to see if new issues emerge when using packages under Linux.

**Comment by LHMarshall** [comment]
Yup for now I just removed mention of linux in the documentation. Dave said he tested it on a Debian machine in a docker container but I don't have it. Also I only see it having a choice between windows and Darwin (mac) for running options therefore at the moment I would say we do not support linux.

**Comment by lenthomas** [comment]
I have marked this as an enhancement.  I agree it's something we should consider for a future version.

**Comment by lenthomas** [comment]
I will close this as we are deprecating the MCDS.exe optimizer.
