### ISSUE TITLE
MCDS.exe generating errors with io mrds models

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#89]
If you install MCDS.exe and then try to run mrds models with detection functions then mrds generates errors from MCDS.exe

A work around is to for mrds to only use the R optimiser for these models.

In the ddf call set the optimizer element of the control argument to "R"

```
ddf(..., control = list(optimizer = 'R'))
```

**Comment by lenthomas** [comment]
@LHMarshall to add code to check for double platform analyses and switch to optimizer = R and give out a warning.  Then switch this issue to enhancement and priority or create new issue.

**Comment by LHMarshall** [comment]
Enhancement list as a new issue #95
