### ISSUE TITLE
Allow users to be able to use the MCDS optimizer for double observer analyses

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/mrds#95]
The MCDS optimiser could be used to estimate the detection function in point independent double observer analyses. 

This was not happening automatically so some debugging would be required to figure out what is going wrong for double observer models.

**Comment by lenthomas** [comment]
I will close this as we are deprecating the MCDS optimizer.

**Comment by erex** [comment]
There should probably be an issue raised about what needs to be done to "deprecate" mcds.exe. Vignettes will change, help documentation will change, even if fossilised code remains in place. We still have lingering code implementations that are listed as "experimental" and we haven't resolve what that means.
